name: quill_delta
description: Dart implementation of Quill editor Delta format.
version: 0.1.0
#homepage: https://www.example.com
#author: Anatoly Pulyaevskiy <email@example.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  collection: ^1.14.5
  quiver_hashcode: ^1.0.0

dev_dependencies:
  test: ^0.12.0
